#端口
server:
  port: 8080
  servlet:
    context-path: /

#spring配置-数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/rent?Unicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true  #热部署
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间转化格式
    time-zone: GMT+8                  #配置时区
  mvc:
    static-path-pattern: /images/** #配置图片上传路径
  resources:
    static-locations: file:D:\images
#Mybatis
mybatis-plus:
  mapper-locations: com/chen/dao/*.xml
  type-aliases-package: com.chen.pojo
  configuration:
    map-underscore-to-camel-case: true #驼峰式
#打印sql日志
logging:
  level:
    com.chen.dao: debug
